'use client';

import { Lock } from 'lucide-react';
import type { LayoutNode, Field } from '@openforge/shared';
import { useRenderContext, useServiceContext, useFieldComponent } from '../hooks';
import { buildFieldExtraProps } from './field-extra-props';

function computeDisplay(field: Field, record: Record<string, any>): string {
  if (field.fieldType === 'USER') {
    return record.displayName || record.username || String(record.id);
  }
  if (field.fieldType === 'ORGANIZATION') {
    return record.name || String(record.id);
  }
  const df = (field.options as any)?.targetDisplayField || 'name';
  return record[df] ?? String(record.id);
}

interface FieldNodeProps {
  node: LayoutNode;
  field?: Field;
}

export function FieldNode({ node, field: fieldProp }: FieldNodeProps) {
  const { mode, fields, fieldMap, data, onChange, errors, t, readonlyColumns } = useRenderContext();
  const services = useServiceContext();

  const field = fieldProp ?? fieldMap.get(node.props?.fieldId ?? '');
  if (!field) return null;

  const Comp = useFieldComponent(field.fieldType);
  const span = node.props?.span ?? 1;
  const columnName = field.columnName;
  const value = data[columnName] ?? field.defaultValue ?? '';
  const error = errors[columnName];
  const isView = mode === 'view';
  const lockedByMaster = (readonlyColumns ?? []).includes(columnName);
  const disabled = isView || field.fieldType === 'AUTO_NUMBER' || lockedByMaster;
  const fieldMode = isView ? 'view' : 'edit';

  const viewRequired = node.props?.required;
  const isRequired = viewRequired != null ? viewRequired : field.isRequired;

  const extraProps = buildFieldExtraProps(field, services, data);
  if (field.fieldType === 'AUTO_NUMBER') {
    extraProps.placeholder = t('designer.autoGenerated');
  }

  // For REFERENCE/USER/ORGANIZATION, let the field emit the full picked record
  // so we can persist id, display, and any sibling LOOKUP-target columns in
  // one go. LOOKUP keeps working in the main form via its reference-record
  // hook, but populating row data too means the value shows even without the
  // cache (and matches the sub-table behavior).
  if (
    field.fieldType === 'REFERENCE' ||
    field.fieldType === 'USER' ||
    field.fieldType === 'ORGANIZATION'
  ) {
    extraProps.onPickRecord = (record: Record<string, any> | null) => {
      if (record == null) {
        onChange(columnName, null);
        onChange(`${columnName}__display`, null);
        for (const f of fields) {
          if (f.fieldType !== 'LOOKUP') continue;
          if ((f.options as any)?.sourceFieldId !== field.id) continue;
          onChange(f.columnName, null);
        }
        return;
      }
      onChange(columnName, record.id);
      onChange(`${columnName}__display`, computeDisplay(field, record));
      for (const f of fields) {
        if (f.fieldType !== 'LOOKUP') continue;
        if ((f.options as any)?.sourceFieldId !== field.id) continue;
        const targetCol = (f.options as any)?.targetFieldColumnName;
        if (!targetCol) continue;
        onChange(f.columnName, record[targetCol] ?? null);
      }
    };
  }

  return (
    <div
      className="space-y-1.5"
      style={{ gridColumn: span > 1 ? `span ${span}` : undefined }}
    >
      <label
        className={`flex items-center gap-1 text-sm font-medium ${
          isView ? 'text-muted-foreground' : 'text-foreground'
        }`}
      >
        <span>{field.name}</span>
        {!isView && isRequired && field.fieldType !== 'AUTO_NUMBER' && (
          <span className="text-red-500">*</span>
        )}
        {lockedByMaster && (
          <span title={t('distribute.fieldReadonlyByMaster')} className="inline-flex shrink-0">
            <Lock className="w-3 h-3 opacity-60" />
          </span>
        )}
      </label>
      {Comp ? (
        <Comp
          field={field}
          value={value}
          onChange={(v: any) => onChange(columnName, v)}
          disabled={disabled}
          error={error}
          mode={fieldMode}
          {...extraProps}
        />
      ) : (
        <div className="h-9 w-full rounded-md border bg-muted/30" />
      )}
      {error && (
        <p className="text-xs text-destructive">{error}</p>
      )}
    </div>
  );
}
