'use client';

import type { LayoutNode, Field } from '@openforge/shared';
import { useRenderContext, useServiceContext, useFieldComponent } from '../hooks';
import { buildFieldExtraProps } from './field-extra-props';

interface FieldNodeProps {
  node: LayoutNode;
  field?: Field;
}

export function FieldNode({ node, field: fieldProp }: FieldNodeProps) {
  const { mode, fieldMap, data, onChange, errors, t } = useRenderContext();
  const services = useServiceContext();

  const field = fieldProp ?? fieldMap.get(node.props?.fieldId ?? '');
  if (!field) return null;

  const Comp = useFieldComponent(field.fieldType);
  const span = node.props?.span ?? 1;
  const columnName = field.columnName;
  const value = data[columnName] ?? field.defaultValue ?? '';
  const error = errors[columnName];
  const isView = mode === 'view';
  const disabled = isView || field.fieldType === 'AUTO_NUMBER';
  const fieldMode = isView ? 'view' : 'edit';

  const viewRequired = node.props?.required;
  const isRequired = viewRequired != null ? viewRequired : field.isRequired;

  const extraProps = buildFieldExtraProps(field, services, data);
  if (field.fieldType === 'AUTO_NUMBER') {
    extraProps.placeholder = t('designer.autoGenerated');
  }

  return (
    <div
      className="space-y-1.5"
      style={{ gridColumn: span > 1 ? `span ${span}` : undefined }}
    >
      <label
        className={`block text-sm font-medium ${
          isView ? 'text-muted-foreground' : 'text-foreground'
        }`}
      >
        {field.name}
        {!isView && isRequired && field.fieldType !== 'AUTO_NUMBER' && (
          <span className="ml-0.5 text-red-500">*</span>
        )}
      </label>
      {Comp ? (
        <Comp
          field={field}
          value={value}
          onChange={(v: any) => onChange(columnName, v)}
          disabled={disabled}
          error={error}
          mode={fieldMode}
          {...extraProps}
        />
      ) : (
        <div className="h-9 w-full rounded-md border bg-muted/30" />
      )}
      {error && (
        <p className="text-xs text-destructive">{error}</p>
      )}
    </div>
  );
}
