/**
 * 业务错误码清单
 *
 * 命名规则：模块_动作_原因（全大写下划线）
 * 前端根据 errorCode 字段映射 i18n key。
 */
export const ErrorCodes = {
  // ── Auth ──
  AUTH_WRONG_PASSWORD: 'AUTH_WRONG_PASSWORD',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_NO_ORGANIZATION: 'AUTH_NO_ORGANIZATION',
  AUTH_INVALID_REFRESH_TOKEN: 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_INVALID_HANDOFF_CODE: 'AUTH_INVALID_HANDOFF_CODE',

  // ── Config ──
  CONFIG_NOT_FOUND: 'CONFIG_NOT_FOUND',

  // ── App ──
  APP_CODE_EXISTS: 'APP_CODE_EXISTS',
  APP_HAS_MODELS: 'APP_HAS_MODELS',
  APP_NOT_FOUND: 'APP_NOT_FOUND',

  // ── Model ──
  MODEL_TABLE_NAME_EXISTS: 'MODEL_TABLE_NAME_EXISTS',
  MODEL_HAS_DATA: 'MODEL_HAS_DATA',
  MODEL_HAS_FIELDS: 'MODEL_HAS_FIELDS',
  MODEL_HAS_REFERENCES: 'MODEL_HAS_REFERENCES',
  MODEL_NOT_FOUND: 'MODEL_NOT_FOUND',

  // ── Entity ──
  ENTITY_NOT_FOUND: 'ENTITY_NOT_FOUND',
  ENTITY_CODE_DUPLICATE: 'ENTITY_CODE_DUPLICATE',
  ENTITY_HAS_DATA: 'ENTITY_HAS_DATA',

  // ── Field ──
  FIELD_COLUMN_NAME_EXISTS: 'FIELD_COLUMN_NAME_EXISTS',
  FIELD_IS_SYSTEM: 'FIELD_IS_SYSTEM',
  FIELD_TYPE_CHANGE_UNSAFE: 'FIELD_TYPE_CHANGE_UNSAFE',
  FIELD_IN_RECYCLE_BIN: 'FIELD_IN_RECYCLE_BIN',
  FIELD_NOT_IN_RECYCLE_BIN: 'FIELD_NOT_IN_RECYCLE_BIN',
  FIELD_NOT_FOUND: 'FIELD_NOT_FOUND',
  FIELD_HAS_NULL_DATA: 'FIELD_HAS_NULL_DATA',
  FIELD_INVALID_RELATION_TARGET: 'FIELD_INVALID_RELATION_TARGET',

  // ── MULTI_REFERENCE ──
  M2M_INVALID_TARGET: 'M2M_INVALID_TARGET',
  M2M_DUPLICATE_RELATION: 'M2M_DUPLICATE_RELATION',

  // ── Dynamic Data ──
  DATA_VERSION_CONFLICT: 'DATA_VERSION_CONFLICT',
  DATA_HAS_REFERENCES: 'DATA_HAS_REFERENCES',
  DATA_NOT_FOUND: 'DATA_NOT_FOUND',
  DATA_VALIDATION_FAILED: 'DATA_VALIDATION_FAILED',
  DATA_UNIQUE_VIOLATION: 'DATA_UNIQUE_VIOLATION',
  DATA_ARCHIVE_FAILED: 'DATA_ARCHIVE_FAILED',

  // ── Children (SubTable) ──
  CHILDREN_INVALID_MODEL: 'CHILDREN_INVALID_MODEL',
  CHILDREN_DELETE_HAS_REFERENCES: 'CHILDREN_DELETE_HAS_REFERENCES',

  // ── Tree ──
  TREE_CIRCULAR_REFERENCE: 'TREE_CIRCULAR_REFERENCE',
  TREE_HAS_CHILDREN: 'TREE_HAS_CHILDREN',
  TREE_INVALID_PARENT: 'TREE_INVALID_PARENT',

  // ── Dict ──
  DICT_CODE_DUPLICATE: 'DICT_CODE_DUPLICATE',
  DICT_NOT_FOUND: 'DICT_NOT_FOUND',
  DICT_IN_USE: 'DICT_IN_USE',
  DICT_ITEM_VALUE_DUPLICATE: 'DICT_ITEM_VALUE_DUPLICATE',
  DICT_ITEM_NOT_FOUND: 'DICT_ITEM_NOT_FOUND',

  // ── View ──
  VIEW_NOT_FOUND: 'VIEW_NOT_FOUND',

  // ── DDL ──
  DDL_UNSAFE_NAME: 'DDL_UNSAFE_NAME',
  DDL_TYPE_CHANGE_UNSAFE: 'DDL_TYPE_CHANGE_UNSAFE',

  // ── File ──
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',

  // ── Distribution ──
  INVALID_OPERATION: 'INVALID_OPERATION',

  // ── Setup ──
  SETUP_ALREADY_INITIALIZED: 'SETUP_ALREADY_INITIALIZED',

  // ── RBAC ──
  FORBIDDEN: 'FORBIDDEN',
  FIELD_FORBIDDEN: 'FIELD_FORBIDDEN',
  MISSING_PERMISSION_DECORATOR: 'MISSING_PERMISSION_DECORATOR',
  ROLE_HAS_USERS: 'ROLE_HAS_USERS',
  ROLE_CODE_DUPLICATE: 'ROLE_CODE_DUPLICATE',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  MENU_NOT_DELETABLE: 'MENU_NOT_DELETABLE',
  MENU_CODE_INVALID: 'MENU_CODE_INVALID',
  MENU_NOT_FOUND: 'MENU_NOT_FOUND',
  MENU_TARGET_MISMATCH: 'MENU_TARGET_MISMATCH',
  MENU_CROSS_APP: 'MENU_CROSS_APP',
  MENU_TARGET_INCONSISTENT: 'MENU_TARGET_INCONSISTENT',
  MODEL_HAS_MENU_REF: 'MODEL_HAS_MENU_REF',
  VIEW_HAS_MENU_REF: 'VIEW_HAS_MENU_REF',
} as const;
