/**
 * 业务错误码清单
 *
 * 命名规则：模块_动作_原因（全大写下划线）
 * 前端根据 errorCode 字段映射 i18n key。
 */
export const ErrorCodes = {
  // ── Auth ──
  AUTH_WRONG_PASSWORD: 'AUTH_WRONG_PASSWORD',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_NO_ORGANIZATION: 'AUTH_NO_ORGANIZATION',
  AUTH_INVALID_REFRESH_TOKEN: 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_SESSION_REPLACED: 'AUTH_SESSION_REPLACED',

  // ── Config ──
  CONFIG_NOT_FOUND: 'CONFIG_NOT_FOUND',

  // ── App ──
  APP_CODE_EXISTS: 'APP_CODE_EXISTS',
  APP_HAS_MODELS: 'APP_HAS_MODELS',
  APP_NOT_FOUND: 'APP_NOT_FOUND',

  // ── Model ──
  MODEL_TABLE_NAME_EXISTS: 'MODEL_TABLE_NAME_EXISTS',
  MODEL_HAS_DATA: 'MODEL_HAS_DATA',
  MODEL_HAS_FIELDS: 'MODEL_HAS_FIELDS',
  MODEL_HAS_REFERENCES: 'MODEL_HAS_REFERENCES',
  MODEL_NOT_FOUND: 'MODEL_NOT_FOUND',

  // ── Entity ──
  ENTITY_NOT_FOUND: 'ENTITY_NOT_FOUND',
  ENTITY_CODE_DUPLICATE: 'ENTITY_CODE_DUPLICATE',
  ENTITY_HAS_DATA: 'ENTITY_HAS_DATA',

  // ── Field ──
  FIELD_COLUMN_NAME_EXISTS: 'FIELD_COLUMN_NAME_EXISTS',
  FIELD_IS_SYSTEM: 'FIELD_IS_SYSTEM',
  FIELD_TYPE_NOT_ALLOWED_IN_ENTITY: 'FIELD_TYPE_NOT_ALLOWED_IN_ENTITY',
  FIELD_TYPE_CHANGE_UNSAFE: 'FIELD_TYPE_CHANGE_UNSAFE',
  FIELD_IN_RECYCLE_BIN: 'FIELD_IN_RECYCLE_BIN',
  FIELD_NOT_IN_RECYCLE_BIN: 'FIELD_NOT_IN_RECYCLE_BIN',
  FIELD_NOT_FOUND: 'FIELD_NOT_FOUND',
  FIELD_HAS_NULL_DATA: 'FIELD_HAS_NULL_DATA',
  FIELD_INVALID_RELATION_TARGET: 'FIELD_INVALID_RELATION_TARGET',

  // ── LOOKUP ──
  FIELD_NOT_WRITABLE: 'FIELD_NOT_WRITABLE',
  LOOKUP_SOURCE_FIELD_NOT_FOUND: 'LOOKUP_SOURCE_FIELD_NOT_FOUND',
  LOOKUP_SOURCE_TYPE_INVALID: 'LOOKUP_SOURCE_TYPE_INVALID',
  LOOKUP_SOURCE_MUST_BE_SAME_RECORD: 'LOOKUP_SOURCE_MUST_BE_SAME_RECORD',
  LOOKUP_TARGET_TYPE_NOT_ALLOWED: 'LOOKUP_TARGET_TYPE_NOT_ALLOWED',
  FIELD_HAS_DEPENDENT_LOOKUPS: 'FIELD_HAS_DEPENDENT_LOOKUPS',

  // ── MULTI_REFERENCE ──
  M2M_INVALID_TARGET: 'M2M_INVALID_TARGET',
  M2M_DUPLICATE_RELATION: 'M2M_DUPLICATE_RELATION',

  // ── Dynamic Data ──
  DATA_VERSION_CONFLICT: 'DATA_VERSION_CONFLICT',
  DATA_HAS_REFERENCES: 'DATA_HAS_REFERENCES',
  DATA_NOT_FOUND: 'DATA_NOT_FOUND',
  DATA_VALIDATION_FAILED: 'DATA_VALIDATION_FAILED',
  DATA_UNIQUE_VIOLATION: 'DATA_UNIQUE_VIOLATION',
  DATA_ARCHIVE_FAILED: 'DATA_ARCHIVE_FAILED',
  DATA_STATUS_INVALID_TRANSITION: 'DATA_STATUS_INVALID_TRANSITION',
  DATA_STATUS_NOT_SUBMITTER: 'DATA_STATUS_NOT_SUBMITTER',
  DATA_STATUS_NOT_ENABLED: 'DATA_STATUS_NOT_ENABLED',
  DATA_STATUS_NOT_EDITABLE: 'DATA_STATUS_NOT_EDITABLE',

  // ── Children (SubTable) ──
  CHILDREN_INVALID_MODEL: 'CHILDREN_INVALID_MODEL',
  CHILDREN_DELETE_HAS_REFERENCES: 'CHILDREN_DELETE_HAS_REFERENCES',

  // ── Tree ──
  TREE_CIRCULAR_REFERENCE: 'TREE_CIRCULAR_REFERENCE',
  TREE_HAS_CHILDREN: 'TREE_HAS_CHILDREN',
  TREE_INVALID_PARENT: 'TREE_INVALID_PARENT',

  // ── Dict ──
  DICT_CODE_DUPLICATE: 'DICT_CODE_DUPLICATE',
  DICT_NOT_FOUND: 'DICT_NOT_FOUND',
  DICT_IN_USE: 'DICT_IN_USE',
  DICT_ITEM_VALUE_DUPLICATE: 'DICT_ITEM_VALUE_DUPLICATE',
  DICT_ITEM_NOT_FOUND: 'DICT_ITEM_NOT_FOUND',

  // ── View ──
  VIEW_NOT_FOUND: 'VIEW_NOT_FOUND',

  // ── DDL ──
  DDL_UNSAFE_NAME: 'DDL_UNSAFE_NAME',
  DDL_TYPE_CHANGE_UNSAFE: 'DDL_TYPE_CHANGE_UNSAFE',

  // ── File ──
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',

  // ── Distribution ──
  INVALID_OPERATION: 'INVALID_OPERATION',

  // ── Setup ──
  SETUP_ALREADY_INITIALIZED: 'SETUP_ALREADY_INITIALIZED',

  // ── Action ──
  ACTION_NOT_FOUND: 'ACTION_NOT_FOUND',
  ACTION_SYSTEM_NOT_DELETABLE: 'ACTION_SYSTEM_NOT_DELETABLE',
  ACTION_CODE_DUPLICATE: 'ACTION_CODE_DUPLICATE',

  // ── RBAC ──
  FORBIDDEN: 'FORBIDDEN',
  FIELD_FORBIDDEN: 'FIELD_FORBIDDEN',
  MISSING_PERMISSION_DECORATOR: 'MISSING_PERMISSION_DECORATOR',
  ROLE_HAS_USERS: 'ROLE_HAS_USERS',
  ROLE_CODE_DUPLICATE: 'ROLE_CODE_DUPLICATE',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  MENU_NOT_DELETABLE: 'MENU_NOT_DELETABLE',
  MENU_CODE_INVALID: 'MENU_CODE_INVALID',
  MENU_NOT_FOUND: 'MENU_NOT_FOUND',
  MENU_TARGET_MISMATCH: 'MENU_TARGET_MISMATCH',
  MENU_CROSS_APP: 'MENU_CROSS_APP',
  MENU_TARGET_INCONSISTENT: 'MENU_TARGET_INCONSISTENT',
  MODEL_HAS_MENU_REF: 'MODEL_HAS_MENU_REF',
  VIEW_HAS_MENU_REF: 'VIEW_HAS_MENU_REF',

  // ── User ──
  USERNAME_EXISTS: 'USERNAME_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_CANNOT_MODIFY_ADMIN: 'USER_CANNOT_MODIFY_ADMIN',
  USER_CANNOT_DELETE_ADMIN: 'USER_CANNOT_DELETE_ADMIN',
  USER_CANNOT_DELETE_LOGGED_IN: 'USER_CANNOT_DELETE_LOGGED_IN',
  USER_DEFAULT_ORG_NOT_IN_LIST: 'USER_DEFAULT_ORG_NOT_IN_LIST',
  USER_ORG_NOT_FOUND: 'USER_ORG_NOT_FOUND',
  USER_ORG_IS_GROUP: 'USER_ORG_IS_GROUP',

  // ── Org ──
  ORG_GROUP_CANNOT_BE_ROOT: 'ORG_GROUP_CANNOT_BE_ROOT',
  CANNOT_ALLOCATE_TO_GROUP: 'CANNOT_ALLOCATE_TO_GROUP',

  // ── P2.2 — Org isolation + Distribution ──
  ORG_ACCESS_DENIED: 'ORG_ACCESS_DENIED',
  DISTRIBUTE_REQUIRES_ROOT_ORG: 'DISTRIBUTE_REQUIRES_ROOT_ORG',
  MODEL_NOT_DISTRIBUTED: 'MODEL_NOT_DISTRIBUTED',
  NOT_A_MASTER_RECORD: 'NOT_A_MASTER_RECORD',
  CANNOT_ALLOCATE_TO_ROOT: 'CANNOT_ALLOCATE_TO_ROOT',
  ALREADY_ALLOCATED: 'ALREADY_ALLOCATED',
  COPY_NOT_FOUND: 'COPY_NOT_FOUND',
  FIELD_READONLY_BY_MASTER: 'FIELD_READONLY_BY_MASTER',
  CANNOT_CREATE_COPY_DIRECTLY: 'CANNOT_CREATE_COPY_DIRECTLY',
  CANNOT_DELETE_COPY: 'CANNOT_DELETE_COPY',
  CONFIRMATION_MISMATCH: 'CONFIRMATION_MISMATCH',

  // ── P2.3 — Workflow / Approval ──
  WORKFLOW_NOT_FOUND: 'WORKFLOW_NOT_FOUND',
  WORKFLOW_VERSION_NOT_FOUND: 'WORKFLOW_VERSION_NOT_FOUND',
  WORKFLOW_INVALID_DEFINITION: 'WORKFLOW_INVALID_DEFINITION',
  WORKFLOW_DELETE_HAS_INSTANCES: 'WORKFLOW_DELETE_HAS_INSTANCES',
  WORKFLOW_INSTANCE_NOT_FOUND: 'WORKFLOW_INSTANCE_NOT_FOUND',
  WORKFLOW_INSTANCE_NOT_RUNNING: 'WORKFLOW_INSTANCE_NOT_RUNNING',
  WORKFLOW_TASK_NOT_FOUND: 'WORKFLOW_TASK_NOT_FOUND',
  WORKFLOW_TASK_NOT_PENDING: 'WORKFLOW_TASK_NOT_PENDING',
  WORKFLOW_TASK_NOT_ASSIGNEE: 'WORKFLOW_TASK_NOT_ASSIGNEE',
  WORKFLOW_CONCURRENT_UPDATE: 'WORKFLOW_CONCURRENT_UPDATE',
  WORKFLOW_NO_MATCHING_WORKFLOW: 'WORKFLOW_NO_MATCHING_WORKFLOW',
  WORKFLOW_WITHDRAW_HAS_APPROVAL: 'WORKFLOW_WITHDRAW_HAS_APPROVAL',
  WORKFLOW_UNDO_DECISION_TOO_LATE: 'WORKFLOW_UNDO_DECISION_TOO_LATE',
  WORKFLOW_URGE_TOO_FREQUENT: 'WORKFLOW_URGE_TOO_FREQUENT',
  WORKFLOW_ADD_SIGNER_SELF: 'WORKFLOW_ADD_SIGNER_SELF',
  WORKFLOW_RETURN_NO_PREVIOUS: 'WORKFLOW_RETURN_NO_PREVIOUS',
  WORKFLOW_CONDITION_NO_MATCH: 'WORKFLOW_CONDITION_NO_MATCH',
  WORKFLOW_ASSIGNEE_RESOLVE_FAILED: 'WORKFLOW_ASSIGNEE_RESOLVE_FAILED',
  WORKFLOW_ACTION_NOT_ALLOWED: 'WORKFLOW_ACTION_NOT_ALLOWED',
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
} as const;
